import './index.html';
import './scss/index.scss';
import 'skeleton-css/css/skeleton.css';
import name from './templates/main.template';
import './templates/p5/intro.p5';
import disaplyLinks from './templates/linksSection/links.template';
import disaplySkills from './templates/skillsSection/skills.template';
name.displayName();
disaplyLinks();
disaplySkills();
